### ISSUE TITLE
PSM Extraction is broken

### ISSUE THREAD

**Issue by devnoname120** [weaknespase/PkgDecrypt#11]
Starting from the commit https://github.com/weaknespase/PkgDecrypt/commit/e9138bc82bacd5fd965e35e249fdf95bb8f7bcf, the extraction of PSM PKG leads to a segmentation fault.

Example: http://zeus.dl.playstation.net/psm/np/NPOA/NPOA00013_00_7DD8D995/1.03/NPOA00013_00.pkg

**Comment by weaknespase** [comment]
Thank you for the report, i'll look into the issue.

**Comment by weaknespase** [comment]
Should be fixed now, in 1d8f141298e4267c3aa5ae80e63f6ff3a3dfcf51.

PSM PKGs don't have PSF-formatted metadata in them, changed sfo reader to be more resilient to empty parameters or invalid arguments and made it output empty string instead of null pointer.
