### ISSUE TITLE
PSM extraction with `--make-dirs=ux` produce wrong layout

### ISSUE THREAD

**Issue by devnoname120** [weaknespase/PkgDecrypt#14]
It produces something like this:
```
 app
  └── NPXA00xxx
      ├── contents
      |     └── Application
      |           └── ...
      └── sce_sys
```

Expected:

```
 psm
  └── NPXA00xxx
      ├── RO
      |     ├── Application
      |     |     └── ...
      |     └── License
      |           └── FAKE.rif
      └── RW
            ├── Documents
            ├── System
            |     └── content_id <-- Contains the full id string for example EM0041-NPOA00013_00-0000000000000000
            |     └── pm.dat
            └── Temp

```

**Comment by weaknespase** [comment]
Noted, will work on it, thank you for the guide to directory structure.

**Comment by weaknespase** [comment]
Haven't found `pm.dat` inside PKGs, do you know how it generated?

**Comment by devnoname120** [comment]
> Writing package parts in the `sce_sys/package` directory is intended.

Which is it intended for PSM games?

**Comment by weaknespase** [comment]
It's not intended for games, it's intended as part of tool. In this particular installation scheme it isn't required, but in some other might be.
