### ISSUE TITLE
DLC unpack failure

### ISSUE THREAD

**Issue by kkaazzee** [weaknespase/PkgDecrypt#9]
Hi @weaknespase and crew. Thank you for everything you do.

I'm a Mac user. I've been writing a node JS CLI front end to `pkg_dec` to automate queue/download/decrypt. The Linux release files aren't built in a way friendly to Macs so I've been building from source. I don't mean to add burden. I'm hoping you can make sense of the error I'm encountering.

## Steps to reproduce

* Pull/download `master` at bcc02b2 or the source zip on the 1.2.1 release.
* Run `make all`
  * The build completes with lint warnings.
  * The build binary shows version 1.2.0 instead of 1.2.1
* Run `pkc_dec` on a local PKG
  * bcc02b2: [gist](https://gist.github.com/kkaazzee/c655aaf297c4f2c199ff1f60f5830c5e)
  * 1.2.1: [gist](https://gist.github.com/kkaazzee/2f967f14f25e2c1bb94e9dd0470056b6)
  * The process may be completing but notice the `Abort trap: 6`

I've had no run time errors decrypting games. Only these vocaloid DLC are troublesome. The spreadsheet isn't welcoming viewers to provide other details.

Thanks for any feedback. :+1:

**Comment by weaknespase** [comment]
Thank you for the input, can you try to build and use 2e66830461a9e2dc31a19fd5e490535bf2c99280?

**Comment by kkaazzee** [comment]
Hi @weaknespase 👋 .

2e66830 is showing 1.2.2 now. I still [hit the same `Abort trap: 6`](https://gist.github.com/kkaazzee/01c7591531f5dac0ab360140b291e768). 

It definitely seems to affect only DLC. I hit the same error on other DLC content. Extracting games is always good. I left more tokens in the output this time in case it helps locate the assets I'm testing against.

Thanks a lot for your reply + brain cells. :)

**Comment by weaknespase** [comment]
Seems to happen in the last stage - on PDB generation for shell to pick up DLCs as ready to be installed.

Did you try to unpack DLC in other `--dirs-mode`, `id` for example?

**Comment by kkaazzee** [comment]
Good question. I see the same error with `--make-dirs=id`. I should have included [these logs](https://gist.github.com/kkaazzee/eb10f9d415a10e88f4008f9326fdf0ec) earlier. 😅 

I'm happy to run an instrumented build or run some code edits myself with pointers. I'm a JS coder by profession but I'm comfortable with really basic C++.

**Comment by weaknespase** [comment]
Can you run build with `-Wall` and share build log?

**Comment by kkaazzee** [comment]
Most definitely. First is the log you requested. Second is another pass without `-W` as an update for my earlier log. These are still from 2e66830:

* [`make clean && make -Wall && pkg_dec`](https://gist.github.com/kkaazzee/15c596156fb756a4367ef3cbf05fd6bd)
* [`make clean && make all && pkg_dec`](https://gist.github.com/kkaazzee/ab7e98fae10bebd17fe0d8a7222b9eaa)

**Comment by weaknespase** [comment]
Nope, don't see anything criminal which supposed to prevent it from working (or trying to access unknown territory). 
There are only one thing left to try. Add printf in the beginning of `pkgdbGenerate` in the `pkgdb.c` to check arguments passed to the function, then try to unpack some dlc.
```
printf( "PDB_GEN(0x%p, %u, 0x%p, 0x%p, 0x%p, 0x%p, %llu, %u)\n", buffer, length, title, title_id, pkg_name, pkg_url, pkg_size, install_id );
```

**Comment by weaknespase** [comment]
Try this commit: eeb0c7a9da839d2815eabfbfaab9a95957dee565

**Comment by kkaazzee** [comment]
Bug is still hiding on eeb0c7a: https://gist.github.com/kkaazzee/7989f791214903f3794c754d9ec0488a

I'm heading into work now, I'll be back online in ~10hrs. When I return I'll instrument the code tonight to help with the bug hunt.

Thank s @weaknespase!

**Comment by weaknespase** [comment]
Ok, ping me in Discord then, weaknespase#4259, we'll do something with it

**Comment by kkaazzee** [comment]
Isolated the issue. Success/failure is determined by: https://github.com/weaknespase/PkgDecrypt/blob/master/pkg_dec.c#L643.

It's interesting. The `strcpy` is copying one string to another. Both strings already have identical values before `strcpy` is called. I'm used to JS and its interned strings. 

Look for `Before strcpy` and `After strcpy` in the logs below. The latter will only occur in the second logs. In the second logs I commented out the `strcpy` in it's entirety:

![screen shot 2017-10-11 at 9 02 54 pm](https://user-images.githubusercontent.com/32631717/31482999-644444a0-aec6-11e7-94ba-925ba2e5b7dd.png)

Before: https://gist.github.com/kkaazzee/30dc8a7dd360667d160f5c3272d70ea5

After: https://gist.github.com/kkaazzee/cc9e14e4e0152c71658fad58bb5bbdd2

Apologies for the clumsy hyperlink/screenshot dance. I'm setup with Gitlab for personal projects. I need to add a Github account for sane fork/diff sharing.

Any idea what's up?

**Comment by kkaazzee** [comment]
Using: `strncpy( temp, output_dir, 1024 );` instead of `strcpy( temp, output_dir );` also does the trick. Full disclaimer: I matching syntax and Googling on the side. The code _works_ but I have no idea if it's _correct_.

**Comment by weaknespase** [comment]
Try latest commit 660acf117dc1afa21502f767c04b5668f1d97d31. I think it was an overlapping memory locations issue.

**Comment by kkaazzee** [comment]
HI @weaknespase the issue is gone in 660acf1. Huge thanks!
